# Generated by Django 5.0.3 on 2024-10-04 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(choices=[('Casa', 'Casa'), ('Contas', 'Contas'), ('Alimentação', 'Alimentação'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Lazer', 'Lazer'), ('Compras', 'Compras'), ('Viagem', 'Viagem'), ('Serviços', 'Serviços'), ('Vestuário', 'Vestuário'), ('Impostos', 'Impostos'), ('Transporte', 'Transporte'), ('Investimentos', 'Investimentos'), ('Outros', 'Outros')], default='categoria1', max_length=20, verbose_name='Categoria')),
                ('title', models.CharField(max_length=30, verbose_name='Título')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('payment_method', models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Voucher', 'Voucher'), ('Crediário', 'Crediário'), ('Transferência', 'Transferência'), ('Cartão de loja', 'Cartão de loja')], default='Dinheiro', max_length=20, verbose_name='Forma de Pagamento (Opcional)')),
                ('observation', models.TextField(blank=True, max_length=60, verbose_name='Observação')),
                ('duration_months', models.IntegerField(default=1, verbose_name='Duração em Meses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
