# Generated by Django 4.2.7 on 2024-03-02 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "Despesa", "verbose_name_plural": "Despesas"},
        ),
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Título"),
        ),
    ]
