# Generated by Django 5.0.3 on 2024-03-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('credito', 'Crédito'), ('debito', 'Débito')], default='dinheiro', max_length=20),
            preserve_default=False,
        ),
    ]
