# Generated by Django 5.0.3 on 2024-03-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Crédito', 'Crédito'), ('Débito', 'Débito')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
