# Generated by Django 5.0.3 on 2024-03-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_observation_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ExpenseCategory',
            field=models.CharField(choices=[('categoria1', 'Categoria 1'), ('categoria2', 'Categoria 2'), ('categoria3', 'Categoria 3')], default='categoria1', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='observation',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Voucher', 'Voucher'), ('Crediário', 'Crediário'), ('Transferência', 'Transferência'), ('Cartão de loja', 'Cartão de loja')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
    ]
