# Generated by Django 5.0.3 on 2024-03-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_expensecategory_alter_expense_observation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='ExpenseCategory',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('Habitação', 'Habitação'), ('Contas', 'Contas'), ('Alimentação', 'Alimentação'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Lazer', 'Lazer'), ('Compras', 'Compras'), ('Serviços', 'Serviços'), ('Impostos', 'Impostos'), ('Transporte', 'Transporte'), ('Investimentos', 'Investimentos'), ('Outros', 'Outros')], default='categoria1', max_length=20, verbose_name='Categoria'),
        ),
    ]
