# Generated by Django 5.0.3 on 2024-04-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expense_expensecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='duration_months',
            field=models.IntegerField(default=1, verbose_name='Duração em Meses'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Contas', 'Contas'), ('Alimentação', 'Alimentação'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Lazer', 'Lazer'), ('Compras', 'Compras'), ('Viagem', 'Viagem'), ('Serviços', 'Serviços'), ('Vestuário', 'Vestuário'), ('Impostos', 'Impostos'), ('Transporte', 'Transporte'), ('Investimentos', 'Investimentos'), ('Outros', 'Outros')], default='categoria1', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='observation',
            field=models.TextField(blank=True, max_length=60, verbose_name='Observação'),
        ),
    ]
